//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        public int id { get; set; }
        [RegularExpression(@"^.{10,11}$")]
        [Required(ErrorMessage = "Numberphone is empty")]
        public string numberphone { get; set; }
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]
        [Required(ErrorMessage = "Password is empty")]
        [DataType(DataType.Password)]
        public string pwd { get; set; }
        [Required(ErrorMessage = "Confirm password is empty")]
        [DataType(DataType.Password)]
        [Compare("pwd")]
        public string confirm_pwd { get; set; }
    }
}
